// Đường dẫn: src/data.js
export const productsData = [
  { 
    id: 1, 
    name: "Cơm Rang Đặc Biệt", 
    price: 38000, 
    oldPrice: 45000, 
    remain: "Còn 100/300 suất", 
    image: "/p1.jpg",
    images: ["/p1.jpg", "/1.1.jpeg", "/1.2.jpg"],
    rating: "4.8",
    reviews: 125,
    description: "Món cơm rang đặc biệt với hạt cơm tơi xốp, kết hợp cùng các loại topping thượng hạng.",
    tags: ["Bán chạy", "Đặc biệt"],
    ingredients: ["Gạo thơm", "Xá xíu", "Lạp xưởng", "Tôm khô", "Đậu Hà Lan", "Cà rốt", "Trứng gà"],
    instruction: "Cơm được nấu chín và để nguội để hạt săn lại. Sau đó rang trên lửa lớn cùng các loại topping cho đến khi thơm nức."
  },
  { 
    id: 2, 
    name: "Cơm Rang Kiểu Trung", 
    price: 52000, 
    oldPrice: 60000, 
    remain: "Còn 5/20 suất", 
    image: "/p2.jpg",
    images: ["/p2.jpg", "/2.1.jpg", "/2.2.jpg"],
    rating: "4.5",
    reviews: 80,
    description: "Cơm rang chuẩn vị Trung Hoa, thơm mùi xì dầu và dầu mè.",
    tags: ["Mới", "Đậm vị"],
    ingredients: ["Gạo hạt dài", "Thịt xá xíu", "Trứng gà tươi", "Hành lá", "Xì dầu thượng hạng"],
    instruction: "Sử dụng xì dầu đặc trưng và dầu mè thơm nồng. Cơm được rang liên tục trên chảo gang sâu lòng."
  },
  { 
    id: 3, 
    name: "Cơm Chiên Hải Sản (hot)", 
    price: 150000, 
    oldPrice: 200000, 
    remain: "Sắp hết hàng", 
    image: "/p3.jpg",
    images: ["/p3.jpg", "/3.1.jpg", "/3.2.jpg"],
    rating: "4.9",
    reviews: 210,
    description: "Sự kết hợp giữa cơm chiên giòn rụm và hải sản tươi sống (mực, tôm, cồi sò điệp).",
    tags: ["Hot", "Hải sản"],
    ingredients: ["Tôm tươi", "Mực ống", "Cồi sò điệp", "Cơm trắng", "Trứng muối"],
    instruction: "Hải sản được xào sơ để giữ độ ngọt. Cơm chiên cùng lòng đỏ trứng muối tạo độ bùi và màu vàng đẹp mắt."
  },
  { 
    id: 4, 
    name: "Cơm Cuộn", 
    price: 15000, 
    oldPrice: 30000, 
    remain: "Còn 10/30 suất", 
    image: "/p4.jpg",
    images: ["/p4.jpg", "/4.1.jpg", "/4.2.jpg"],
    rating: "4.2",
    reviews: 45,
    description: "Cơm cuộn truyền thống với rong biển giòn, bên trong là nhân xúc xích, dưa chuột.",
    tags: ["Ăn nhẹ", "Giá rẻ"],
    ingredients: ["Rong biển khô", "Gạo dẻo", "Xúc xích", "Dưa chuột", "Trứng chiên"],
    instruction: "Cơm dẻo được dàn mỏng trên lá rong biển, xếp các nguyên liệu nhân vào giữa và cuộn chặt tay bằng mành tre."
  },
  { 
    id: 5, 
    name: "Cơm Cuộn Kiểu Nhật", 
    price: 52000, 
    oldPrice: 60000, 
    remain: "Còn 5/20 suất", 
    image: "/p5.jpg",
    images: ["/p5.jpg", "/5.1.jpg", "/5.2.jpg"],
    rating: "4.7",
    reviews: 95,
    description: "Sushi cuộn kiểu Nhật tinh tế, sử dụng gạo Nhật hạt tròn mềm dẻo, nhân cá hồi tươi.",
    tags: ["Nhật Bản", "Sang trọng"],
    ingredients: ["Gạo Nhật Shari", "Cá hồi tươi", "Bơ sáp", "Giấm Nhật", "Mè rang"],
    instruction: "Gạo sau khi nấu được trộn cùng giấm chuyên dụng. Nhân cá hồi và bơ được chọn lựa kỹ lưỡng."
  },
  { 
    id: 6, 
    name: "Cơm Hải Sản Đặc Biệt", 
    price: 200000, 
    oldPrice: 250000, 
    remain: "Sắp hết hàng", 
    image: "/p6.jpg",
    images: ["/p6.jpg", "/6.1.jpg", "/6.2.jpg"],
    rating: "5.0",
    reviews: 320,
    description: "Phần cơm hải sản siêu to khổng lồ dành cho 2-3 người ăn.",
    tags: ["Premium", "Khổng lồ"],
    ingredients: ["Tôm hùm baby", "Cua biển", "Mực ống", "Vẹm xanh", "Cơm chiên tỏi"],
    instruction: "Các loại hải sản cao cấp được hấp chín tới để giữ độ mọng nước, bày trí lên phần cơm chiên tỏi."
  },
  { 
    id: 7, 
    name: "Cơm Văn Phòng", 
    price: 30000, 
    oldPrice: 45000, 
    remain: "Còn 300/300 suất", 
    image: "/p7.jpg",
    images: ["/p7.jpg", "/7.1.jpg", "/7.2.jpg"],
    rating: "4.0",
    reviews: 512,
    description: "Suất cơm văn phòng đầy đặn, đủ chất dinh dưỡng với món mặn, rau xào.",
    tags: ["Tiết kiệm", "Buổi trưa"],
    ingredients: ["Thịt kho/Gà chiên", "Rau theo mùa", "Canh nóng", "Trái cây tráng miệng"],
    instruction: "Nguyên liệu được nhập mới mỗi sáng, chế biến theo quy trình sạch sẽ tại bếp nhà hàng."
  },
  { 
    id: 8, 
    name: "Cơm Rang Trứng", 
    price: 15000, 
    oldPrice: 20000, 
    remain: "Còn 20/20 suất", 
    image: "/p8.jpg",
    images: ["/p8.jpg", "/8.1.jpg", "/8.2.jpg"],
    rating: "4.3",
    reviews: 110,
    description: "Món ăn giản dị nhưng cực kỳ đưa miệng. Cơm rang vàng ươm cùng trứng gà ta.",
    tags: ["Truyền thống", "Nhanh chóng"],
    ingredients: ["Cơm nguội", "Trứng gà ta", "Hành lá", "Gia vị cơ bản"],
    instruction: "Đánh tan trứng và trộn đều vào cơm trước khi rang để từng hạt cơm đều được bao phủ lớp trứng."
  },
  { 
    id: 9, 
    name: "Cơm Sườn Chả (hot)", 
    price: 50000, 
    oldPrice: 70000, 
    remain: "Sắp hết hàng", 
    image: "/p9.jpeg",
    images: ["/p9.jpeg", "/9.1.jpg", "/9.2.jpg"],
    rating: "4.8",
    reviews: 405,
    description: "Cơm tấm sườn nướng mỡ hành thơm nức mũi, kèm theo chả trứng hấp béo ngậy.",
    tags: ["Sài Gòn", "Đặc trưng"],
    ingredients: ["Gạo tấm", "Sườn heo cốt lết", "Chả trứng", "Mỡ hành", "Đồ chua"],
    instruction: "Sườn được ướp gia vị và nướng trên than hồng. Gạo tấm được hấp chín. Ăn kèm nước mắm chua ngọt."
  },
  { 
    id: 10, 
    name: "Cơm Rang Dưa Bò", 
    price: 35000, 
    oldPrice: 40000, 
    remain: "Còn 30/30 suất", 
    image: "/p10.jpeg",
    images: ["/p10.jpeg", "/10.1.jpg", "/10.2.jpg"],
    rating: "4.6",
    reviews: 230,
    description: "Cơm rang dưa chua giòn sần sật, xào cùng thịt bò thăn mềm ngọt.",
    tags: ["Hà Nội", "Đậm đà"],
    ingredients: ["Thịt bò thăn", "Dưa cải chua", "Cơm trắng", "Tỏi băm"],
    instruction: "Thịt bò xào nhanh tay trên lửa lớn. Dưa chua vắt kiệt nước rồi rang cùng cơm cho đến khi giòn."
  },
  { 
    id: 11, 
    name: "Cơm Cari", 
    price: 50000, 
    oldPrice: 60000, 
    remain: "Còn 5/20 suất", 
    image: "/p11.png",
    images: ["/p11.png", "/11.1.jpg", "/11.2.jpg"],
    rating: "4.4",
    reviews: 88,
    description: "Cơm trắng dẻo thơm ăn kèm sốt cà ri kiểu Ấn Độ sánh mịn.",
    tags: ["Cay nhẹ", "Ấn Độ"],
    ingredients: ["Bột cà ri Ấn", "Thịt gà", "Khoai tây", "Nước cốt dừa", "Gạo dẻo"],
    instruction: "Hầm thịt gà và khoai tây trong nước sốt cà ri cùng nước cốt dừa cho đến khi sánh đặc."
  },
  { 
    id: 12, 
    name: "Cơm Xá Xíu", 
    price: 100000, 
    oldPrice: 250000, 
    remain: "Sắp hết hàng", 
    image: "/p12.jpg",
    images: ["/p12.jpg", "/12.1.jpg", "/12.2.jpg"],
    rating: "4.7",
    reviews: 156,
    description: "Thịt xá xíu nướng mật ong bóng bẩy, thái lát mỏng vừa ăn.",
    tags: ["Thịt nướng", "Mật ong"],
    ingredients: ["Thịt nạc vai", "Mật ong rừng", "Ngũ vị hương", "Nước sốt xá xíu"],
    instruction: "Thịt nạc vai được tẩm ướp cùng mật ong và nướng trong lò cho đến khi cháy cạnh."
  }
];